name: Pull request title check

on:
  pull_request:

permissions:
  contents: read

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect title
        run: echo "${{ github.event.pull_request.title }}"
